### PR TITLE
Add a test for maps to test equality of key/values

### PR DESCRIPTION
**Pull request by mrnovalles**

### CODE REVIEW

**Review by eproxus — APPROVED** [review]

**Comment by eproxus** [comment]
Hi @mrnovalles! Long time no see 😉 Thanks for the PR! 🙌

**Review by eproxus — CHANGES_REQUESTED** [review]
Could you add a comment for why this test is needed? Also (depending on the reason) would it make sense to test with unequal maps?

**Comment by mrnovalles** [comment]
Hey! I'm sorry this was not suppose to show up this early. The test was related to this other issue in Elixir's mock: https://github.com/jjh42/mock/issues/141

**Comment by eproxus** [comment]
Ah, I'll close this PR for now then 😄 Feel free to re-open it (or a new one) if you have something you want to contribute.

**Pull request closed without merging**
